language: go
go:
  - 1.5
  - tip

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq imagemagick

services: mongodb

install:
  - go get github.com/yvasiyarov/gorelic
  - go get launchpad.net/gocheck
  - go get gopkg.in/mgo.v2
  - go get github.com/disintegration/imaging
  - go get github.com/nfnt/resize
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/context
