language: go
go:
  - 1.2

install:
  - go get code.google.com/p/graphics-go/graphics
  - go get launchpad.net/gocheck
  - go get labix.org/v2/mgo 
  - go get github.com/gorilla/mux
  - ln -s $TRAVIS_BUILD_DIR $GOPATH/src/voycer.com
