language: go
go:
  - 1.5
  - tip

before_install:
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
  - sudo apt-get install -qq imagemagick
  - sudo apt-get install libcv-dev libopencv-dev libopencv-contrib-dev libhighgui-dev libopencv-photo-dev libopencv-imgproc-dev libopencv-stitching-dev libopencv-superres-dev libopencv-ts-dev libopencv-videostab-dev

services: mongodb

install:
    - go get -t -d -v ./...
    - go get github.com/onsi/ginkgo/ginkgo
    - go get -u github.com/golang/lint/golint

script:
    - ginkgo -r -cover --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress
    - scripts/fmtpolice
